[project]
name = "2025-08-09-rags"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastembed>=0.7.1",
    "qdrant-client>=1.15.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
